name: build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Build plugin
        run: ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: build-${{ github.run_number }}
          files: app/build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
